# Generated by Django 3.2.4 on 2022-07-11 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='orders',
            field=models.ManyToManyField(related_name='food_items', through='foodDelivery.OrderFoodItem', to='foodDelivery.Order'),
        ),
        migrations.AlterField(
            model_name='orderfooditem',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodDelivery.fooditem'),
        ),
        migrations.AlterField(
            model_name='orderfooditem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodDelivery.order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderfooditem',
            unique_together={('order', 'food_item')},
        ),
    ]
