# Generated by Django 3.2.4 on 2022-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('actor', 'movie'), name='role'),
        ),
    ]
