# Generated by Django 3.2.4 on 2022-07-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_auto_20220709_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='moviedb.Role', to='moviedb.Movie'),
        ),
    ]
