# Generated by Django 3.2.4 on 2022-07-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0004_actor_movie'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='role',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('actor', 'movie')},
        ),
    ]
